package dev.praneeth.backend.Hospitalization;

// import org.springframework.boot.CommandLineRunner;
// import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

// import java.time.LocalDate;
// import java.util.List;

@Configuration
public class HospitalizationConfig {

    /*@Bean
    CommandLineRunner commandLineRunner(HospitalizationRepository repository) {
        return args -> {
            Hospitalization hospitalization1 = new Hospitalization(
                    1, // HospitalizationID (autogenerated, can be omitted if using auto increment)
                    LocalDate.of(2024, 1, 12), // Admission date
                    null, // Discharge date (nullable)
                    "Fracture", // Reason for hospitalization
                    "Surgery scheduled", // Notes
                    1 // PatientID (referencing an existing user/patient)
            );

            Hospitalization hospitalization2 = new Hospitalization(
                    2, // HospitalizationID
                    LocalDate.of(2023, 10, 20), // Admission date
                    LocalDate.of(2023, 10, 25), // Discharge date
                    "Pneumonia", // Reason
                    "Follow-up needed in 2 weeks", // Notes
                    2 // PatientID
            );

            // Save the initial hospitalizations to the database
            repository.saveAll(List.of(hospitalization1, hospitalization2));
        };
    }*/
}

